### ISSUE TITLE
Please bump the version with 3.5 python support

### ISSUE THREAD

**Issue by XVilka** [Iotic-Labs/py-ubjson#3]
To be available from pip.

**Comment by vtermanis** [comment]
Hi,

v0.8.4 (which is available via pip) should work with Python 3.5 (I just tried it with 3.5.1 under Ubuntu 14.04 & Windows 7). As you can see from c1d6037e, nothing else has changed to support 3.5 (since the most recent release of py-ubjson, which is the previous commit).
Do you get an error when trying to install/import/run it?

Regards,
VT

**Comment by XVilka** [comment]
pip installs it, but says there is no such module.

**Comment by vtermanis** [comment]
Ah, maybe you're affected by [this bug](https://github.com/pypa/pip/issues/3056). (This sort of thing happens to me on CentOS 7 x64 - no error if not running in verbose mode but module is not installed.)

Can you try:
```shell
# In case something was installed
pip3 uninstall py-ubjson
# This will prevent usage of C extension
PYUBJSON_NO_EXTENSION=1 python3 setup.py install
```

**Comment by XVilka** [comment]
Yes, this helped.

Kind regards,
XVilka.
